name: main

on:
  push:
    paths:
      - '**'
      - '!.github/workflows/cross.yml'
      - '!.github/workflows/ow-libc.yml'
      - '!tools/*'
#  pull_request:
#    paths:
#     - '**'
#     - '!.github/workflows/cross.yml'
#     - '!.github/workflows/ow-libc.yml'
#     - '!tools/*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: setup
        run: 'sudo apt-get install texinfo libncurses5-dev libelf-dev ncompress'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: cross
          key: cross-${{ hashFiles('tools/*') }}-${{ runner.os }}

      - name: prepare
        if: steps.cache.outputs.cache-hit != 'true'
        run: 'mkdir -p cross'

      - name: cross
        if: steps.cache.outputs.cache-hit != 'true'
        run: tools/build.sh

      - name: Open Watcom setup
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0-64"

      - name: environ
        run: |
            echo $WATCOM
            echo $PATH

      - name: build
        run: ./build.sh auto allimages

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: fd1440.img
          path: image/fd1440.img

      - name: upload2
        uses: actions/upload-artifact@v4
        with:
          name: fd360-minix.img
          path: image/fd360-minix.img

      - name: upload3
        uses: actions/upload-artifact@v4
        with:
          name: fd720-minix.img
          path: image/fd720-minix.img

      - name: upload4
        uses: actions/upload-artifact@v4
        with:
          name: fd1200-minix.img
          path: image/fd1200-minix.img

      - name: upload5
        uses: actions/upload-artifact@v4
        with:
          name: fd1440-minix.img
          path: image/fd1440-minix.img

      - name: upload6
        uses: actions/upload-artifact@v4
        with:
          name: fd2880-minix.img
          path: image/fd2880-minix.img

      - name: upload7
        uses: actions/upload-artifact@v4
        with:
          name: hd32-minix.img
          path: image/hd32-minix.img

      - name: upload8
        uses: actions/upload-artifact@v4
        with:
          name: hd32mbr-minix.img
          path: image/hd32mbr-minix.img

      - name: upload9
        uses: actions/upload-artifact@v4
        with:
          name: fd360-fat.img
          path: image/fd360-fat.img

      - name: upload10
        uses: actions/upload-artifact@v4
        with:
          name: fd720-fat.img
          path: image/fd720-fat.img

      - name: upload11
        uses: actions/upload-artifact@v4
        with:
          name: fd1200-fat.img
          path: image/fd1200-fat.img

      - name: upload12
        uses: actions/upload-artifact@v4
        with:
          name: fd1440-fat.img
          path: image/fd1440-fat.img

      - name: upload13
        uses: actions/upload-artifact@v4
        with:
          name: fd2880-fat.img
          path: image/fd2880-fat.img

      - name: upload14
        uses: actions/upload-artifact@v4
        with:
          name: hd32-fat.img
          path: image/hd32-fat.img

      - name: upload15
        uses: actions/upload-artifact@v4
        with:
          name: hd32mbr-fat.img
          path: image/hd32mbr-fat.img

      - name: upload16
        uses: actions/upload-artifact@v4
        with:
          name: hd64-minix.img
          path: image/hd64-minix.img

      - name: upload17
        uses: actions/upload-artifact@v4
        with:
          name: hd64mbr-minix.img
          path: image/hd64mbr-minix.img

      - name: upload18
        uses: actions/upload-artifact@v4
        with:
          name: fd1232.img
          path: image/fd1232.img
